//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicPower.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Artist
    {
        public string ArtistId { get; set; }
        public string ArtistName { get; set; }
        public string ArtistGenre { get; set; }
        public string ArtistBio { get; set; }
    }
}
